name: Python tests

on:
  push:
  pull_request:

jobs:
  python-tests:
    name: Python tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if requirements.txt exists)
        if: hashFiles('**/requirements.txt') != ''
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (opcional) agrega src al PYTHONPATH si lo necesitas
      # - name: Add src to PYTHONPATH
      #   run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      - name: Run pytest
        run: pytest -q tests
