name: Python tests

on:
  push:
  pull_request:

jobs:
  python-tests:          # 👈 nombre interno del job
    name: Python tests   # 👈 este es el nombre que aparecerá en GitHub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest
        run: pytest -q
